
name: Build and Publish

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Download application
        run: curl -L -o calculadora.zip https://s3.i02.estaleiro.serpro.gov.br/rtccalc-repo-apr/calculadora.zip

      - name: Unzip application
        run: |
          unzip calculadora.zip
          mkdir src
          unzip codigo-fonte-backend.zip -d src

      - name: Commit and push changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add src
          git commit -m "Add backend source code"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
